
#ami:  ami-accff2b1
ami: ami-f1d7c395
region: eu-west-2
ansible_ssh_private_key_file: ~/.ssh/aviva17.pem
location: london
key: aviva17
role: mgmt-a17
host_role: mgmt-a17

env_name: 'szkolenie_a17'

#allow change VPC (routing)
allow_vpc_change: True

# VPC
szkolenie_vpc: 
    vpc:
        name: szkolenie_a17
        cidr_block: 10.221.0.0/24
        subnets:
          - cidr: 10.221.0.0/25
            resource_tags:
                Name: szkolenie_pub_a17
    route:
      - subnets:
          - 10.221.0.0/25
        routes:
          - dest: 0.0.0.0/0
            gw: igw
        resource_tags:
          Name:  szkolenie default route a17

    security_groups:
        name: szkolenie-security-group-a17
        description: szkolenie SG a17
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 89.70.92.47/32
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 87.206.148.14/32
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 89.70.92.163/32
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 89.70.90.8/32
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 212.67.156.30/32   #muszynski homeA
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 10.218.0.0/24 
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 52.56.207.120/32 #mgmt 
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 37.47.5.11/32 #kubagprs
          - proto: icmp
            from_port: -1
            to_port: -1
            cidr_ip: 0.0.0.0/0
    ec2_eip:
        instance_A:
          tag: 1A
          ip: 35.176.70.226
          name: 'mgmt-server-a17'
    instance_group: szkolenie1a17
